---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app: gitserver
  name: gitserver-deployment
  namespace: team-support
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitserver
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: ~
      labels:
        app: gitserver
    spec:
      containers:
        -
          image: quay.io/ivancherepov/git-server
          imagePullPolicy: Always
          name: gitserver
          ports:
            -
              containerPort: 4000
              protocol: TCP
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: ivanquaysecret
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
